version: "3.8"

services:
  db:
    image: postgres:15
    container_name: movie_catalog_db
    restart: always
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
      POSTGRES_DB: movie_catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: movie_catalog_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://catalog_user:catalog_password@db:5432/movie_catalog
      - SECRET_KEY=b3d9f131a980998a44490f230bbd743a13915bc828882ca1a6b0c20ab0d9e262
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db

volumes:
  postgres_data:
